### ISSUE TITLE
trying to follow instructions

### ISSUE THREAD

**Issue by jajourda** [prismicio/baked.js#16]
I keep getting errors when trying to follow the instructions as worded.

**Comment by jajourda** [comment]
crappy critique on my part: so here goes:
1. git clone https://github.com/prismicio/baked.js.git
2. cd baked.js
3.  npm install -g baked
4. npm install (this is for the installation of the package.json file's contents, most of which goes into node_modules)
5. run "baked"
-i am within the root directory of the project, and get the response: Config file not found
Ne mangez pas trop vite

**Comment by jajourda** [comment]
ok, so changed approach. kind of getting further... here are the instructions i am using now:
*( already ran "npm install -g baked")
1. git clone https://github.com/prismicio/baked.js.git
2. cd baked.js/examples/blank
3.baked
4.npm install
5. gulp serve
6. navigate to http://127.0.0.1:8282/
7. i see access denied.

any advice, i will keep tinkering.

**Comment by dohzya** [comment]
Hi,

thank you for your feedback :-)

For the 1st example: the https://github.com/prismicio/baked.js repository is the source code, not a ready-to-generate website's sources. That's why it didn't work: it had nothing to generate. There was an old `to_generate` directory which made you believe the opposite, I'm sorry for that (I removed it). Your second guess to go in examples was right :-)

The `blank` example is a template, to create your own website. So it did work. But nothing was generated since there are no files in it. Alas there is a problem in the dev web server we use: it returns “access denied” instead of “not found”. So it worked but the error message made you believe it didn't.

Note: the `baked` command used to get sources in the `to_generate` repository by default. I pushed the version 0.2.0 which fixes that.

So you have 2 ways to quickly try baked.js:

- with `baked`
  1. update your `baked` command with `npm install -f baked`
  2. go to `examples/vanilla`
  3. run `baked`
  4. look in the `generated/` directory
- with `gulp`
  1. go to `examples/stylus`
  2. run `npm install`
  3. run `gulp serve`

Note: the “required and assigne” logs are tests from the website source file, not error log from `baked` itself.

I hope there explications will help you :-)

**Comment by amos-whitewolf** [comment]
Hey, first comment/post on Github so go easy on me :P.

I've been trying to get the examples going. I had success with the vanilla example, but having trouble with both the stylus and blank examples. I'm getting the same error when i run gulp serve on both of them.

blank$ gulp serve
[14:16:09] Using gulpfile ~/websites/gleamers/prismic/baked.js/examples/blank/gulpfile.js
[14:16:09] Starting 'baked:init'...
[14:16:09] 'baked:init' errored after 657 μs
[14:16:09] TypeError: Cannot read property 'srcDir' of undefined
    at init (/Users/dev/websites/gleamers/prismic/baked.js/examples/blank/node_modules/baked/gulp.js:52:18)
    at Gulp.<anonymous> (/Users/dev/websites/gleamers/prismic/baked.js/examples/blank/node_modules/baked/gulp.js:87:7)
    at module.exports (/Users/dev/websites/gleamers/prismic/baked.js/examples/blank/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/dev/websites/gleamers/prismic/baked.js/examples/blank/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/dev/websites/gleamers/prismic/baked.js/examples/blank/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/dev/websites/gleamers/prismic/baked.js/examples/blank/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)

**Comment by amos-whitewolf** [comment]
Hey, first time posting/commenting on github.

Trying to get the examples running by following the instructions. I've had luck with the baked command on all three examples, but i keep getting the same error on all of the examples when using the gulp command. I had a quick look into where the errors where coming from and i don't understand why the errors are appearing, so i'm assuming i'm doing something wrong and would like some assistance. 

gulp
[14:49:59] Using gulpfile ~/websites/gleamers/prismic/baked.js/examples/blank/gulpfile.js
[14:49:59] Starting 'baked:init'...
[14:49:59] 'baked:init' errored after 598 μs
[14:49:59] TypeError: Cannot read property 'srcDir' of undefined
    at init (/Users/dev/websites/gleamers/prismic/baked.js/examples/blank/node_modules/baked/gulp.js:52:18)
    at Gulp.<anonymous> (/Users/dev/websites/gleamers/prismic/baked.js/examples/blank/node_modules/baked/gulp.js:87:7)
    at module.exports (/Users/dev/websites/gleamers/prismic/baked.js/examples/blank/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/dev/websites/gleamers/prismic/baked.js/examples/blank/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/dev/websites/gleamers/prismic/baked.js/examples/blank/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/dev/websites/gleamers/prismic/baked.js/examples/blank/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)

**Comment by dohzya** [comment]
Hi, and thanks for you message!

I must say love your assumptions! :-D
However it seems that the problem is on our side ;-)

There was a problem with default gulp helpers. We fixed it in the last version but the `package.json` file of the examples hasn't been updated accordingly… It's now done thanks to you.

Can you update your examples (or just update the version of the “`baked`” dependency from `0.2.1` to `0.3.0` in the `package.json` file) and try again?
I confess I'd love to hear that it works that way, but if it doesn't just tell me and we'll start hunting :-)

**Comment by amos-whitewolf** [comment]
Hey Dohzya,

Sorry that i removed my comment, i tried it again after you committed yesterday and it worked perfectly. More assumptions on my end :P, and didn't want to waste your time. Thanks heaps for fixing that up, and explaining what was wrong, really helpful :).

**Comment by dohzya** [comment]
Haha, no problem… and without your removed comment (actually the 1st one :p) the fix would take longer and maybe more people would have experience your problem… so thanks to you ;-)

**Comment by dohzya** [comment]
@jajourda do you still have problems?
(can I close this issue or can I help? :p)

**Comment by tdurand** [comment]
Running baked in the examples/vanilla directory give me the following error:

```
required and assigned: { myFunc: [Function] }
2015-07-07T14:37:13.552Z - error: render file '/Users/tdurand/Documents/ProjetFreelance/ExpeditionColombia/baked.js/examples/vanilla/index.html' null ... ERROR [2075ms]
2015-07-07T14:37:13.553Z - error: static render file '/Users/tdurand/Documents/ProjetFreelance/ExpeditionColombia/baked.js/examples/vanilla/index.html' null ... ERROR [2124ms]
ReferenceError: ejs:23
    21|     <!-- otherwise the javascript part will failed the 2nd time it will called -->
    22|     [% require("myLib.js", {noCache: true}) %]
 >> 23|     [% console.log("required and fetched from global:", myLib) %]
    24|
    25|     <div><a href="[%= pathTo('search', {typ: 'product', tag: 'Featured', page: 1}) %]">
    26|       Search

myLib is not defined
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/baked/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:29:1058)
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/baked/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:29:1408)
    at /usr/local/lib/node_modules/baked/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/usr/local/lib/node_modules/baked/node_modules/ejs/lib/ejs.js:293:13)
    at render (/usr/local/lib/node_modules/baked/src/baked.js:50:18)
    at evalmachine.<anonymous>:1:1
    at renderTemplate (/usr/local/lib/node_modules/baked/src/baked.js:53:15)
    at renderContent (/usr/local/lib/node_modules/baked/src/baked.js:61:12)
    at /usr/local/lib/node_modules/baked/src/baked.js:237:24
    at _fulfilled (/usr/local/lib/node_modules/baked/node_modules/q/q.js:834:54)
1 errors:

/Users/tdurand/Documents/ProjetFreelance/ExpeditionColombia/baked.js/examples/vanilla/index.html:  { [ReferenceError: ejs:23
    21|     <!-- otherwise the javascript part will failed the 2nd time it will called -->
    22|     [% require("myLib.js", {noCache: true}) %]
 >> 23|     [% console.log("required and fetched from global:", myLib) %]
    24|
    25|     <div><a href="[%= pathTo('search', {typ: 'product', tag: 'Featured', page: 1}) %]">
    26|       Search

myLib is not defined] path: undefined }
/Users/tdurand/Documents/ProjetFreelance/ExpeditionColombia/baked.js/examples/vanilla/generated/index.html args: null
```

**Comment by bbarker** [comment]
@dohzya @tdurand  I too am getting this error, though I ran the following command according to the instructions: `baked --src . --dst ~/tmp/`; Note that "." (currrent directory) is just a copy of `vanilla').

Here's the complete output:

```
brandon@BEBSURFACEPRO3:~/workspace/bbarker.github.io/src$ baked --src . --dst ~/tmp/
required and assigned: { myFunc: [Function] }
2016-10-03T14:52:07.246Z - error: render file './index.html' null ... ERROR [395ms]
2016-10-03T14:52:07.247Z - error: static render file './index.html' null ... ERROR [441ms]
ReferenceError: ejs:23
    21|     <!-- otherwise the javascript part will failed the 2nd time it will called -->
    22|     [% require("myLib.js", {noCache: true}) %]
 >> 23|     [% console.log("required and fetched from global:", myLib) %]
    24|
    25|     <div><a href="[%= pathTo('search', {typ: 'product', tag: 'Featured', page: 1}) %]">
    26|       Search

myLib is not defined
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/baked/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:29:1058)
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/baked/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:29:1408)
    at /usr/local/lib/node_modules/baked/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/usr/local/lib/node_modules/baked/node_modules/ejs/lib/ejs.js:293:13)
    at render (/usr/local/lib/node_modules/baked/src/baked.js:50:18)
    at evalmachine.<anonymous>:1:1
    at renderTemplate (/usr/local/lib/node_modules/baked/src/baked.js:53:15)
    at renderContent (/usr/local/lib/node_modules/baked/src/baked.js:61:12)
    at /usr/local/lib/node_modules/baked/src/baked.js:237:24
    at _fulfilled (/usr/local/lib/node_modules/baked/node_modules/q/q.js:834:54)
1 errors:

./index.html:  { [ReferenceError: ejs:23
    21|     <!-- otherwise the javascript part will failed the 2nd time it will called -->
    22|     [% require("myLib.js", {noCache: true}) %]
 >> 23|     [% console.log("required and fetched from global:", myLib) %]
    24|
    25|     <div><a href="[%= pathTo('search', {typ: 'product', tag: 'Featured', page: 1}) %]">
    26|       Search

myLib is not defined] path: undefined }
/home/brandon/tmp/index.html args: null
```
